-- Freight Malawi — Supabase PostgreSQL schema
-- Production database target: Supabase PostgreSQL
-- Run this file against the target database before starting the backend.

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS vehicles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  license_plate VARCHAR(20) NOT NULL,
  driver_name VARCHAR(100),
  fuel_tank_capacity NUMERIC(8,2) NOT NULL DEFAULT 400.00 CHECK (fuel_tank_capacity > 0),
  device_id VARCHAR(64) UNIQUE,
  device_key_hash VARCHAR(255),
  payload_capacity_kg NUMERIC(10,2) NOT NULL DEFAULT 10000.00 CHECK (payload_capacity_kg > 0),
  overspeed_threshold_kmh NUMERIC(5,2) NOT NULL DEFAULT 80.00 CHECK (overspeed_threshold_kmh BETWEEN 20 AND 180),
  idle_threshold_minutes INTEGER NOT NULL DEFAULT 10 CHECK (idle_threshold_minutes > 0),
  route_key VARCHAR(50),
  current_status VARCHAR(20) NOT NULL DEFAULT 'OFFLINE'
    CHECK (current_status IN ('MOVING','IDLE','STOPPED','OFFLINE')),
  last_latitude NUMERIC(9,6),
  last_longitude NUMERIC(9,6),
  last_gps_update TIMESTAMPTZ,
  last_seen_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vehicles_user ON vehicles(user_id);
CREATE INDEX IF NOT EXISTS idx_vehicles_status ON vehicles(current_status);

CREATE TABLE IF NOT EXISTS trips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  vehicle_id BIGINT NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  status VARCHAR(30) NOT NULL DEFAULT 'PENDING_DETAILS'
    CHECK (status IN ('ACTIVE','PENDING_DETAILS','ROUTE_COMPLETED','COMPLETED','CANCELLED')),
  route_key VARCHAR(50),
  origin VARCHAR(150),
  destination VARCHAR(150),
  route_name VARCHAR(100),
  cargo_type VARCHAR(100),
  cargo_description TEXT,
  cargo_weight_kg NUMERIC(10,2) CHECK (cargo_weight_kg IS NULL OR cargo_weight_kg >= 0),
  distance_km NUMERIC(10,2) CHECK (distance_km IS NULL OR distance_km >= 0),
  transporter_income NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (transporter_income >= 0),
  fuel_cost NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (fuel_cost >= 0),
  fuel_used_litres NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (fuel_used_litres >= 0),
  start_fuel_litres NUMERIC(10,2),
  start_odometer_km NUMERIC(12,2),
  end_odometer_km NUMERIC(12,2),
  idle_seconds INTEGER NOT NULL DEFAULT 0 CHECK (idle_seconds >= 0),
  max_speed_kmh NUMERIC(6,2) NOT NULL DEFAULT 0,
  started_at TIMESTAMPTZ,
  ignition_started_at TIMESTAMPTZ,
  ignition_ended_at TIMESTAMPTZ,
  route_completed_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_trips_user ON trips(user_id);
CREATE INDEX IF NOT EXISTS idx_trips_vehicle ON trips(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_trips_status ON trips(status);
CREATE INDEX IF NOT EXISTS idx_trips_vehicle_status ON trips(vehicle_id, status);
CREATE INDEX IF NOT EXISTS idx_trips_route ON trips(route_key);

CREATE TABLE IF NOT EXISTS telemetry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telemetry_uuid VARCHAR(64) NOT NULL UNIQUE,
  vehicle_id BIGINT NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  trip_id BIGINT REFERENCES trips(id) ON DELETE SET NULL,
  latitude NUMERIC(9,6) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
  longitude NUMERIC(9,6) NOT NULL CHECK (longitude BETWEEN -180 AND 180),
  speed NUMERIC(6,2) NOT NULL DEFAULT 0 CHECK (speed BETWEEN 0 AND 250),
  heading NUMERIC(5,1) NOT NULL DEFAULT 0 CHECK (heading BETWEEN 0 AND 360),
  fuel_level_litres NUMERIC(8,2) NOT NULL CHECK (fuel_level_litres >= 0),
  fuel_percent NUMERIC(5,2) NOT NULL CHECK (fuel_percent BETWEEN 0 AND 100),
  odometer_km NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (odometer_km >= 0),
  engine_hours NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (engine_hours >= 0),
  ignition_on BOOLEAN NOT NULL DEFAULT FALSE,
  cargo_weight_kg NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (cargo_weight_kg >= 0),
  gps_valid BOOLEAN NOT NULL DEFAULT TRUE,
  recorded_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_telemetry_vehicle_time ON telemetry(vehicle_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_telemetry_trip ON telemetry(trip_id);

CREATE TABLE IF NOT EXISTS trip_expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id BIGINT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  category VARCHAR(40) NOT NULL CHECK (category IN (
    'Fuel','Toll','Food','Accommodation','Maintenance','Loading','Offloading',
    'Driver Allowance','Parking','Other'
  )),
  description VARCHAR(255),
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  expense_date DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_expenses_trip ON trip_expenses(trip_id);

CREATE TABLE IF NOT EXISTS alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  vehicle_id BIGINT NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  trip_id BIGINT REFERENCES trips(id) ON DELETE SET NULL,
  category VARCHAR(20) NOT NULL CHECK (category IN ('FUEL','DRIVER','SAFETY','LOAD','ROUTE','TRIP','SYSTEM')),
  type VARCHAR(50) NOT NULL,
  severity VARCHAR(10) NOT NULL DEFAULT 'MEDIUM' CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
  message TEXT NOT NULL,
  meta JSONB,
  acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
  acknowledged_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alerts_user ON alerts(user_id);
CREATE INDEX IF NOT EXISTS idx_alerts_trip ON alerts(trip_id);
CREATE INDEX IF NOT EXISTS idx_alerts_vehicle ON alerts(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_alerts_user_ack ON alerts(user_id, acknowledged);
CREATE INDEX IF NOT EXISTS idx_alerts_created ON alerts(created_at DESC);

CREATE TABLE IF NOT EXISTS driver_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id BIGINT NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  trip_id BIGINT REFERENCES trips(id) ON DELETE SET NULL,
  event_type VARCHAR(50) NOT NULL,
  severity VARCHAR(10) NOT NULL DEFAULT 'MEDIUM' CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
  speed_kmh NUMERIC(6,2),
  details JSONB,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_driver_events_vehicle ON driver_events(vehicle_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_driver_events_trip ON driver_events(trip_id);

CREATE TABLE IF NOT EXISTS device_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id BIGINT NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  action VARCHAR(50) NOT NULL,
  details JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_device_actions_vehicle ON device_actions(vehicle_id, created_at DESC);

CREATE OR REPLACE FUNCTION freight_touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION freight_touch_updated_at();

DROP TRIGGER IF EXISTS trg_vehicles_updated_at ON vehicles;
CREATE TRIGGER trg_vehicles_updated_at BEFORE UPDATE ON vehicles
FOR EACH ROW EXECUTE FUNCTION freight_touch_updated_at();

DROP TRIGGER IF EXISTS trg_trips_updated_at ON trips;
CREATE TRIGGER trg_trips_updated_at BEFORE UPDATE ON trips
FOR EACH ROW EXECUTE FUNCTION freight_touch_updated_at();
